/**
 * Sample data for the Creative Suite application
 */

import {
  BookOpen,
  Bookmark,
  Brush,
  Camera,
  Code,
  CuboidIcon,
  FileText,
  Grid,
  Home,
  ImageIcon,
  Layers,
  LayoutGrid,
  Palette,
  Sparkles,
  Type,
  Users,
  Video,
  CheckCircle,
  AlertTriangle,
  Info,
  XCircle,
} from "lucide-react"

import type {
  App,
  RecentFile,
  Project,
  Tutorial,
  CommunityPost,
  Notification,
  Message,
  CloudStorage,
  UserProfile,
} from "../types"

export const APPS: App[] = [
  {
    name: "PixelMaster",
    icon: <ImageIcon className="text-violet-500" />,
    description: "Advanced image editing and composition",
    category: "Creative",
    recent: true,
    new: false,
    progress: 100,
  },
  {
    name: "VectorPro",
    icon: <Brush className="text-orange-500" />,
    description: "Professional vector graphics creation",
    category: "Creative",
    recent: true,
    new: false,
    progress: 100,
  },
  {
    name: "VideoStudio",
    icon: <Video className="text-pink-500" />,
    description: "Cinematic video editing and production",
    category: "Video",
    recent: true,
    new: false,
    progress: 100,
  },
  {
    name: "MotionFX",
    icon: <Sparkles className="text-blue-500" />,
    description: "Stunning visual effects and animations",
    category: "Video",
    recent: false,
    new: false,
    progress: 100,
  },
  {
    name: "PageCraft",
    icon: <Layers className="text-red-500" />,
    description: "Professional page design and layout",
    category: "Creative",
    recent: false,
    new: false,
    progress: 100,
  },
  {
    name: "UXFlow",
    icon: <LayoutGrid className="text-fuchsia-500" />,
    description: "Intuitive user experience design",
    category: "Design",
    recent: false,
    new: true,
    progress: 85,
  },
  {
    name: "PhotoLab",
    icon: <Camera className="text-teal-500" />,
    description: "Advanced photo editing and organization",
    category: "Photography",
    recent: false,
    new: false,
    progress: 100,
  },
  {
    name: "DocMaster",
    icon: <FileText className="text-red-600" />,
    description: "Document editing and management",
    category: "Document",
    recent: false,
    new: false,
    progress: 100,
  },
  {
    name: "WebCanvas",
    icon: <Code className="text-emerald-500" />,
    description: "Web design and development",
    category: "Web",
    recent: false,
    new: true,
    progress: 70,
  },
  {
    name: "3DStudio",
    icon: <CuboidIcon className="text-indigo-500" />,
    description: "3D modeling and rendering",
    category: "3D",
    recent: false,
    new: true,
    progress: 60,
  },
  {
    name: "FontForge",
    icon: <Type className="text-amber-500" />,
    description: "Typography and font creation",
    category: "Typography",
    recent: false,
    new: false,
    progress: 100,
  },
  {
    name: "ColorPalette",
    icon: <Palette className="text-purple-500" />,
    description: "Color scheme creation and management",
    category: "Design",
    recent: false,
    new: false,
    progress: 100,
  },
]

export const RECENT_FILES: RecentFile[] = [
  {
    name: "Brand Redesign.pxm",
    app: "PixelMaster",
    modified: "2 hours ago",
    icon: <ImageIcon className="text-violet-500" />,
    shared: true,
    size: "24.5 MB",
    collaborators: 3,
  },
  {
    name: "Company Logo.vec",
    app: "VectorPro",
    modified: "Yesterday",
    icon: <Brush className="text-orange-500" />,
    shared: true,
    size: "8.2 MB",
    collaborators: 2,
  },
  {
    name: "Product Launch Video.vid",
    app: "VideoStudio",
    modified: "3 days ago",
    icon: <Video className="text-pink-500" />,
    shared: false,
    size: "1.2 GB",
    collaborators: 0,
  },
  {
    name: "UI Animation.mfx",
    app: "MotionFX",
    modified: "Last week",
    icon: <Sparkles className="text-blue-500" />,
    shared: true,
    size: "345 MB",
    collaborators: 4,
  },
  {
    name: "Magazine Layout.pgc",
    app: "PageCraft",
    modified: "2 weeks ago",
    icon: <Layers className="text-red-500" />,
    shared: false,
    size: "42.8 MB",
    collaborators: 0,
  },
  {
    name: "Mobile App Design.uxf",
    app: "UXFlow",
    modified: "3 weeks ago",
    icon: <LayoutGrid className="text-fuchsia-500" />,
    shared: true,
    size: "18.3 MB",
    collaborators: 2,
  },
]

export const PROJECTS: Project[] = [
  {
    name: "Brand Identity Redesign",
    description: "Complete brand overhaul for tech startup",
    progress: 75,
    dueDate: "Dec 15, 2024",
    members: 4,
    files: 23,
  },
  {
    name: "E-commerce Website",
    description: "Modern online store with payment integration",
    progress: 45,
    dueDate: "Jan 20, 2025",
    members: 6,
    files: 67,
  },
  {
    name: "Mobile App UI/UX",
    description: "Cross-platform mobile application design",
    progress: 90,
    dueDate: "Dec 8, 2024",
    members: 3,
    files: 34,
  },
  {
    name: "Marketing Campaign",
    description: "Digital marketing materials and assets",
    progress: 30,
    dueDate: "Jan 5, 2025",
    members: 5,
    files: 18,
  },
]

export const TUTORIALS: Tutorial[] = [
  {
    title: "Getting Started with PixelMaster",
    description: "Learn the basics of professional image editing",
    duration: "45 min",
    level: "Beginner",
    instructor: "Sarah Chen",
    category: "Creative",
    views: "12.5K",
  },
  {
    title: "Advanced Vector Techniques",
    description: "Master complex vector graphics creation",
    duration: "1h 20min",
    level: "Advanced",
    instructor: "Michael Rodriguez",
    category: "Creative",
    views: "8.9K",
  },
  {
    title: "Video Editing Fundamentals",
    description: "Essential skills for video production",
    duration: "2h 15min",
    level: "Intermediate",
    instructor: "Emma Thompson",
    category: "Video",
    views: "15.2K",
  },
  {
    title: "UI/UX Design Principles",
    description: "Create intuitive user experiences",
    duration: "1h 45min",
    level: "Intermediate",
    instructor: "David Kim",
    category: "Design",
    views: "22.1K",
  },
]

export const COMMUNITY_POSTS: CommunityPost[] = [
  {
    title: "Amazing Logo Design Process",
    author: "Sarah Chen",
    likes: 342,
    comments: 28,
    image: "/placeholder.svg?height=300&width=400",
    time: "2 hours ago",
  },
  {
    title: "Typography Tips for Beginners",
    author: "Michael Rodriguez",
    likes: 189,
    comments: 15,
    image: "/placeholder.svg?height=300&width=400",
    time: "5 hours ago",
  },
  {
    title: "Color Theory in Practice",
    author: "Emma Thompson",
    likes: 276,
    comments: 32,
    image: "/placeholder.svg?height=300&width=400",
    time: "1 day ago",
  },
  {
    title: "UI Dashboard Redesign",
    author: "Thomas Wright",
    likes: 276,
    comments: 32,
    image: "/placeholder.svg?height=300&width=400",
    time: "3 days ago",
  },
  {
    title: "Product Photography Setup",
    author: "Olivia Chen",
    likes: 189,
    comments: 15,
    image: "/placeholder.svg?height=300&width=400",
    time: "5 days ago",
  },
]

export const NOTIFICATIONS: Notification[] = [
  {
    id: "1",
    title: "New App Update Available",
    message: "PixelMaster v2.1 is now available with new AI features",
    time: "2 minutes ago",
    type: "info",
    read: false,
    icon: <Info className="h-4 w-4" />,
  },
  {
    id: "2",
    title: "Project Completed",
    message: "Brand Identity project has been marked as complete",
    time: "1 hour ago",
    type: "success",
    read: false,
    icon: <CheckCircle className="h-4 w-4" />,
  },
  {
    id: "3",
    title: "Storage Almost Full",
    message: "You're using 90% of your cloud storage space",
    time: "3 hours ago",
    type: "warning",
    read: true,
    icon: <AlertTriangle className="h-4 w-4" />,
  },
  {
    id: "4",
    title: "Collaboration Request",
    message: "Sarah Chen invited you to collaborate on Mobile App Design",
    time: "Yesterday",
    type: "info",
    read: true,
    icon: <Users className="h-4 w-4" />,
  },
  {
    id: "5",
    title: "Sync Failed",
    message: "Failed to sync 3 files to cloud storage",
    time: "2 days ago",
    type: "error",
    read: true,
    icon: <XCircle className="h-4 w-4" />,
  },
]

export const MESSAGES: Message[] = [
  {
    id: "1",
    sender: "Sarah Chen",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "Hey! I've finished the logo concepts. Can you review them?",
    time: "5 min ago",
    unread: true,
  },
  {
    id: "2",
    sender: "Design Team",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "Weekly design review meeting scheduled for tomorrow at 2 PM",
    time: "1 hour ago",
    unread: true,
  },
  {
    id: "3",
    sender: "Michael Rodriguez",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "The client approved the wireframes. Moving to visual design phase.",
    time: "3 hours ago",
    unread: false,
  },
  {
    id: "4",
    sender: "Emma Thompson",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "Thanks for the feedback on the typography guide!",
    time: "Yesterday",
    unread: false,
  },
  {
    id: "5",
    sender: "Project Updates",
    avatar: "/placeholder.svg?height=32&width=32",
    message: "3 new files uploaded to Website Redesign project",
    time: "2 days ago",
    unread: false,
  },
]

export const CLOUD_STORAGE: CloudStorage = {
  used: 45.2,
  total: 100,
  files: 1247,
  lastSync: "2 minutes ago",
}

export const USER_PROFILE: UserProfile = {
  name: "John Doe",
  email: "john.doe@designali.com",
  avatar: "/placeholder.svg?height=40&width=40",
  plan: "Pro",
  joinDate: "January 2023",
}
